// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbXpFS2KyNcOUov-jS3bf-NrvU4OUqalk',
    appId: '1:758863528096:web:b12c4f2322f5739ee749c5',
    messagingSenderId: '758863528096',
    projectId: 'scalendar-36991',
    authDomain: 'scalendar-36991.firebaseapp.com',
    storageBucket: 'scalendar-36991.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBda0trIfozvyc2toCO0R-YekAixlIiDB0',
    appId: '1:758863528096:android:4d35d702ccf27581e749c5',
    messagingSenderId: '758863528096',
    projectId: 'scalendar-36991',
    storageBucket: 'scalendar-36991.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-cn0zdMysUg3mgcJoRJG-IaRm-Pg39eI',
    appId: '1:758863528096:ios:61b3717f988beec0e749c5',
    messagingSenderId: '758863528096',
    projectId: 'scalendar-36991',
    storageBucket: 'scalendar-36991.firebasestorage.app',
    iosBundleId: 'com.example.myUrlSummarizerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-cn0zdMysUg3mgcJoRJG-IaRm-Pg39eI',
    appId: '1:758863528096:ios:61b3717f988beec0e749c5',
    messagingSenderId: '758863528096',
    projectId: 'scalendar-36991',
    storageBucket: 'scalendar-36991.firebasestorage.app',
    iosBundleId: 'com.example.myUrlSummarizerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbXpFS2KyNcOUov-jS3bf-NrvU4OUqalk',
    appId: '1:758863528096:web:2988e0e67ad40395e749c5',
    messagingSenderId: '758863528096',
    projectId: 'scalendar-36991',
    authDomain: 'scalendar-36991.firebaseapp.com',
    storageBucket: 'scalendar-36991.firebasestorage.app',
  );

}